# Generated by Django 4.0.5 on 2022-06-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_roomname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='roomname',
            new_name='room_name',
        ),
    ]
