# Generated by Django 4.0.5 on 2022-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_roomname_message_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
