# Generated by Django 4.0.5 on 2022-06-30 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_room_name_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
