# Generated by Django 4.0.5 on 2022-06-30 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
