# Generated by Django 4.0.5 on 2022-06-10 07:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[accounts.models.validate_username], verbose_name='Username'),
        ),
    ]
