# Generated by Django 4.0.5 on 2022-06-14 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_lift', models.IntegerField()),
                ('no_of_floors', models.IntegerField()),
                ('no_of_building', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sqft', models.IntegerField()),
                ('possession', models.CharField(choices=[('Ready to Take', 'Ready to Take'), ('Within 3 months', 'Within 3 months'), ('Within 6 months', 'Within 6 months'), ('Within 12 months', 'Within 12 months')], default='Ready to Take', max_length=50)),
                ('project_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('Constructed', 'Constructed')], default='Constructed', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='HouseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', models.ImageField(upload_to='house_images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.housereview'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
