# Generated by Django 4.0.5 on 2022-06-14 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0002_remove_house_amenities_house_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_review',
        ),
        migrations.AddField(
            model_name='housereview',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='housereview',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
        migrations.AddField(
            model_name='housereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
