# Generated by Django 4.0.5 on 2022-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_likes_likesuser_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='selling_choice',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Buy', max_length=50),
        ),
    ]
