# Generated by Django 4.0.5 on 2022-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_selling_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
