# Generated by Django 4.0.5 on 2022-06-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_house_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
