# Generated by Django 4.0.5 on 2022-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='selling_choice',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=50),
        ),
    ]
