# Generated by Django 4.0.5 on 2022-07-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_likes_set', to='house.house'),
        ),
    ]
