# Generated by Django 4.0.5 on 2022-06-17 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0007_alter_houseimages_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
